languageCode = "en"
languageName = "English"
weight = 1
title = "idea小时"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
   logo = "img/logo.jpg"
  # secondaryLogo = "img/secondary-logo.png"
   description = "My awesome website"
   copyright = "Copy, _right?_ :thinking_face:"

 [author]
   name = "idea小时"
   image = "img/logo.jpg"
   headline = "种一棵树最好的时间是十年前，其次是现在。"
   bio = "A little bit about you"
   links = [
     { email = "mailto:hello@your_domain.com" },
     { link = "https://link-to-some-website.com/" },

     { github = "https://github.com/username" },
     { gitlab = "https://gitlab.com/username" },
     { google = "https://www.google.com/" },
     { hashnode = "https://username.hashnode.dev" },


     { reddit = "https://reddit.com/user/username" },
     { researchgate = "https://www.researchgate.net/profile/username" },
     { slack = "https://workspace.url/team/userid" },
     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
     { steam = "https://steamcommunity.com/profiles/userid" },
     { telegram = "https://t.me/username" },
     { threads = "https://www.threads.net/@username" },
     { twitter = "https://twitter.com/username" },
     { x-twitter = "https://twitter.com/username" },
     { youtube = "https://youtube.com/username" },
     { ko-fi = "https://ko-fi.com/username" },
   ]
